use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;

use glyphon::{FontSystem, SwashCache, TextAtlas, TextRenderer, Viewport};
use wgpu;
use winit::window::Window;

use crate::multiplayer::player::RemotePlayer;
use crate::multiplayer::protocol::Packet;
use crate::ui::menu::{GameState, MenuState};
use minerust::chunk_loader::ChunkLoader;
use minerust::render_core::csm::CsmManager;
use minerust::{Camera, DiggingState, IndirectManager, InputState, World};

pub struct State {
    pub surface: wgpu::Surface<'static>,
    pub device: wgpu::Device,
    pub queue: wgpu::Queue,
    pub config: wgpu::SurfaceConfiguration,
    pub render_pipeline: wgpu::RenderPipeline,
    pub water_pipeline: wgpu::RenderPipeline,
    pub sun_pipeline: wgpu::RenderPipeline,
    pub sky_pipeline: wgpu::RenderPipeline,
    pub shadow_pipeline: wgpu::RenderPipeline,
    pub crosshair_pipeline: wgpu::RenderPipeline,
    pub sun_vertex_buffer: wgpu::Buffer,
    pub sun_index_buffer: wgpu::Buffer,
    pub crosshair_vertex_buffer: wgpu::Buffer,
    pub crosshair_index_buffer: wgpu::Buffer,
    pub num_crosshair_indices: u32,
    pub uniform_buffer: wgpu::Buffer,
    pub uniform_bind_group: wgpu::BindGroup,
    pub shadow_bind_group: wgpu::BindGroup,
    pub depth_texture: wgpu::TextureView,
    pub msaa_texture_view: wgpu::TextureView,
    pub shadow_texture_view: wgpu::TextureView,
    pub shadow_cascade_views: Vec<wgpu::TextureView>,
    pub shadow_cascade_buffer: wgpu::Buffer,
    #[allow(dead_code)]
    pub shadow_sampler: wgpu::Sampler,
    pub world: Arc<parking_lot::RwLock<World>>,
    pub camera: Camera,
    pub input: InputState,
    pub digging: DiggingState,
    pub window: Arc<Window>,
    pub frame_count: u32,
    pub last_fps_update: Instant,
    pub current_fps: f32,
    pub frame_time_ms: f32,
    pub cpu_update_ms: f32,
    pub last_redraw: Instant,
    pub last_frame: Instant,
    pub mouse_captured: bool,
    pub chunks_rendered: u32,
    pub subchunks_rendered: u32,
    pub game_start_time: Instant,
    pub coords_vertex_buffer: Option<wgpu::Buffer>,
    pub coords_index_buffer: Option<wgpu::Buffer>,
    pub coords_num_indices: u32,
    pub last_coords_position: (i32, i32, i32),
    pub progress_bar_vertex_buffer: Option<wgpu::Buffer>,
    pub progress_bar_index_buffer: Option<wgpu::Buffer>,
    #[allow(dead_code)]
    pub texture_atlas: wgpu::Texture,
    #[allow(dead_code)]
    pub texture_view: wgpu::TextureView,
    #[allow(dead_code)]
    pub texture_sampler: wgpu::Sampler,
    pub game_state: GameState,
    pub menu_state: MenuState,
    /// Reflection mode: 0=off, 1=SSR
    pub reflection_mode: u32,
    pub is_underwater: f32,
    pub remote_players: HashMap<u32, RemotePlayer>,
    pub my_player_id: u32,
    pub last_position_send: Instant,
    pub network_runtime: Option<tokio::runtime::Runtime>,
    pub network_rx: Option<tokio::sync::mpsc::UnboundedReceiver<Packet>>,
    pub network_tx: Option<tokio::sync::mpsc::UnboundedSender<Packet>>,
    pub last_input_time: Instant,
    pub player_model_vertex_buffer: Option<wgpu::Buffer>,
    pub player_model_index_buffer: Option<wgpu::Buffer>,
    pub player_model_num_indices: u32,
    pub player_model_vertex_capacity: u32,
    pub player_model_index_capacity: u32,
    pub chunk_loader: ChunkLoader,
    pub last_gen_player_cx: i32,
    pub last_gen_player_cz: i32,
    pub ssr_color_texture: wgpu::Texture,
    pub ssr_color_view: wgpu::TextureView,
    pub ssr_depth_texture: wgpu::Texture,
    pub ssr_depth_view: wgpu::TextureView,
    pub ssr_sampler: wgpu::Sampler,
    pub water_bind_group: wgpu::BindGroup,
    pub water_bind_group_layout: wgpu::BindGroupLayout,
    pub surface_format: wgpu::TextureFormat,
    pub font_system: FontSystem,
    pub swash_cache: SwashCache,
    pub text_atlas: TextAtlas,
    pub text_renderer: TextRenderer,
    pub viewport: Viewport,
    pub fps_buffer: glyphon::Buffer,
    pub menu_title_buffer: glyphon::Buffer,
    pub menu_subtitle_buffer: glyphon::Buffer,
    pub menu_server_label_buffer: glyphon::Buffer,
    pub menu_server_value_buffer: glyphon::Buffer,
    pub menu_username_label_buffer: glyphon::Buffer,
    pub menu_username_value_buffer: glyphon::Buffer,
    pub menu_tips_buffer: glyphon::Buffer,
    pub menu_connect_button_buffer: glyphon::Buffer,
    pub menu_singleplayer_button_buffer: glyphon::Buffer,
    pub menu_status_buffer: glyphon::Buffer,
    pub hotbar_label_buffer: glyphon::Buffer,
    pub hotbar_label_width: f32,
    pub last_hotbar_slot: usize,
    pub player_label_buffers: Vec<glyphon::Buffer>,
    pub mesh_loader: minerust::MeshLoader,
    pub composite_pipeline: wgpu::RenderPipeline,
    pub composite_bind_group: wgpu::BindGroup,
    pub scene_color_texture: wgpu::Texture,
    pub scene_color_view: wgpu::TextureView,
    pub indirect_manager: IndirectManager,
    pub water_indirect_manager: IndirectManager,
    pub hiz_texture: wgpu::Texture,
    pub hiz_view: wgpu::TextureView,
    pub hiz_mips: Vec<wgpu::TextureView>,
    pub hiz_pipeline: wgpu::ComputePipeline,
    pub hiz_bind_groups: Vec<wgpu::BindGroup>,
    pub hiz_bind_group_layout: wgpu::BindGroupLayout,
    pub hiz_size: [u32; 2],
    pub depth_resolve_pipeline: wgpu::RenderPipeline,
    pub depth_resolve_bind_group: wgpu::BindGroup,
    pub supports_indirect_count: bool,
    pub csm: CsmManager,
    pub hotbar_slot: usize,
    pub hotbar_vertex_buffer: Option<wgpu::Buffer>,
    pub hotbar_index_buffer: Option<wgpu::Buffer>,
    pub hotbar_num_indices: u32,
    pub hotbar_dirty: bool,
    pub cursor_position: Option<(f32, f32)>,
}

pub struct WorldSnapshot {
    pub missing_chunks: Vec<(i32, i32, i32)>,
    pub raycast_result: Option<(i32, i32, i32, i32, i32, i32)>,
    pub target_block: Option<minerust::BlockType>,
    pub eye_block: minerust::BlockType,
}

pub struct WorldWriteOps {
    pub completed_chunks: Vec<(i32, i32, minerust::Chunk)>,
    pub block_break: Option<(i32, i32, i32)>,
    pub mark_dirty: Vec<(i32, i32, i32)>,
}
